"""Anatomical-atlas ROI and PCA analysis for SimNIBS gPC results."""

from .atlas_surface import SURFACE_ATLASES, atlas_masks_to_labels, build_surface_roi_summary
from .atlas_volume import (
    DEFAULT_SUBCORTICAL_STRUCTURES,
    VOLUME_ATLAS_FILES,
    build_volume_roi_summary,
    read_freesurfer_lut,
    resolve_freesurfer_lut,
    sample_volume_labels,
    select_volume_roi_labels,
)
from .clinical import (
    attach_subject_info,
    collapse_person_rows,
    compute_cgi_change,
    compute_ef_scaling_factor,
    load_cognitive_scores,
    load_stimulus,
    load_subject_info,
    prepare_scan_course_outcomes,
    prepare_scan_outcomes,
    validate_treatment_courses,
)
from .identifiers import (
    add_subject_id_columns,
    base_subject_id,
    build_scan_table,
    resolve_freesurfer_subjects,
    subject_id_from_path,
)
from .mesh_io import (
    build_hdf5_inventory,
    discover_hdf5_files,
    fsaverage_surface_path,
    inspect_hdf5_mesh,
    load_hdf5_mesh,
    load_surface_mesh,
)
from .pca import (
    ParcelPCA,
    components_for_variance,
    correlate_predictors,
    expand_predictors_to_courses,
    fit_parcel_pca,
    global_and_pc_predictors,
    plot_correlation_bars,
    plot_global_outcome,
    plot_pca_variance,
    plot_subject_parcel_heatmap,
    plot_top_loadings,
)
from .pipeline import AnalysisResult, run_pca_outcome_analysis
from .summary import P95Method, ParcelSummary, global_metrics_from_parcels, weighted_percentile
from .identifiers import infer_subject_id

__all__ = [
    "AnalysisResult",
    "DEFAULT_SUBCORTICAL_STRUCTURES",
    "P95Method",
    "ParcelPCA",
    "ParcelSummary",
    "SURFACE_ATLASES",
    "VOLUME_ATLAS_FILES",
    "add_subject_id_columns",
    "atlas_masks_to_labels",
    "attach_subject_info",
    "base_subject_id",
    "build_hdf5_inventory",
    "build_scan_table",
    "build_surface_roi_summary",
    "build_volume_roi_summary",
    "collapse_person_rows",
    "components_for_variance",
    "compute_cgi_change",
    "compute_ef_scaling_factor",
    "correlate_predictors",
    "discover_hdf5_files",
    "fit_parcel_pca",
    "expand_predictors_to_courses",
    "fsaverage_surface_path",
    "global_and_pc_predictors",
    "global_metrics_from_parcels",
    "inspect_hdf5_mesh",
    "load_cognitive_scores",
    "load_hdf5_mesh",
    "load_stimulus",
    "load_subject_info",
    "load_surface_mesh",
    "plot_correlation_bars",
    "plot_global_outcome",
    "plot_pca_variance",
    "plot_subject_parcel_heatmap",
    "plot_top_loadings",
    "prepare_scan_outcomes",
    "prepare_scan_course_outcomes",
    "read_freesurfer_lut",
    "resolve_freesurfer_lut",
    "resolve_freesurfer_subjects",
    "run_pca_outcome_analysis",
    "sample_volume_labels",
    "select_volume_roi_labels",
    "subject_id_from_path",
    "weighted_percentile",
    "validate_treatment_courses",
]
